services:
  app:                    # The name of the service, can be anything
    image: docker-backend-image # If the image is not found, check Dockerfile in current dir
    build: .              # Declares where to build if image is not found
    ports:                # Declares the ports to publish
      - 3000:3000